apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignite
  namespace: ignite
spec:
  serviceName: ignite
  replicas: 3
  selector:
    matchLabels:
      app: ignite
  template:
    metadata:
      labels:
        app: ignite
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: ignite
          image: apacheignite/ignite:3.0.0
          command:
            - /opt/ignite3/bin/ignite3
          args:
            - --config-path=/etc/ignite/ignite.conf
            - --node-name=$(NODE_NAME)
            - --work-dir=/var/lib/ignite
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3344
              name: internal
            - containerPort: 10300
              name: rest
            - containerPort: 10800
              name: thin
          volumeMounts:
            - name: config
              mountPath: /etc/ignite
            - name: data
              mountPath: /var/lib/ignite
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: config
          configMap:
            name: ignite-config
            items:
              - key: ignite.conf
                path: ignite.conf
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
